// Code generated by protoc-gen-go.
// source: command_queued.proto
// DO NOT EDIT!

/*
Package commandqueued is a generated protocol buffer package.

It is generated from these files:
	command_queued.proto

It has these top-level messages:
	CommandQueued
*/
package commandqueued

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandQueued struct {
	DeviceUdid  string `protobuf:"bytes,1,opt,name=device_udid,json=deviceUdid" json:"device_udid,omitempty"`
	CommandUuid string `protobuf:"bytes,2,opt,name=command_uuid,json=commandUuid" json:"command_uuid,omitempty"`
}

func (m *CommandQueued) Reset()                    { *m = CommandQueued{} }
func (m *CommandQueued) String() string            { return proto.CompactTextString(m) }
func (*CommandQueued) ProtoMessage()               {}
func (*CommandQueued) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandQueued) GetDeviceUdid() string {
	if m != nil {
		return m.DeviceUdid
	}
	return ""
}

func (m *CommandQueued) GetCommandUuid() string {
	if m != nil {
		return m.CommandUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandQueued)(nil), "commandqueued.CommandQueued")
}

func init() { proto.RegisterFile("command_queued.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x89, 0x2f, 0x2c, 0x4d, 0x2d, 0x4d, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x85, 0x8a, 0x42, 0x04, 0x95, 0x82, 0xb9, 0x78, 0x9d, 0x21, 0x02, 0x81, 0x60, 0x01,
	0x21, 0x79, 0x2e, 0xee, 0x94, 0xd4, 0xb2, 0xcc, 0xe4, 0xd4, 0xf8, 0xd2, 0x94, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x2e, 0x88, 0x50, 0x68, 0x4a, 0x66, 0x8a, 0x90, 0x22, 0x17,
	0x0f, 0xcc, 0xe0, 0xd2, 0xd2, 0xcc, 0x14, 0x09, 0x26, 0xb0, 0x0a, 0x6e, 0xa8, 0x58, 0x68, 0x69,
	0x66, 0x4a, 0x12, 0x1b, 0xd8, 0x2a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x34, 0x2e,
	0x49, 0x82, 0x00, 0x00, 0x00,
}
