// Code generated by protoc-gen-go.
// source: push.proto
// DO NOT EDIT!

/*
Package pushproto is a generated protocol buffer package.

It is generated from these files:
	push.proto

It has these top-level messages:
	PushInfo
*/
package pushproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushInfo struct {
	Udid      string `protobuf:"bytes,1,opt,name=udid" json:"udid,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	PushMagic string `protobuf:"bytes,3,opt,name=push_magic,json=pushMagic" json:"push_magic,omitempty"`
	MdmTopic  string `protobuf:"bytes,4,opt,name=mdm_topic,json=mdmTopic" json:"mdm_topic,omitempty"`
}

func (m *PushInfo) Reset()                    { *m = PushInfo{} }
func (m *PushInfo) String() string            { return proto.CompactTextString(m) }
func (*PushInfo) ProtoMessage()               {}
func (*PushInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushInfo) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *PushInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PushInfo) GetPushMagic() string {
	if m != nil {
		return m.PushMagic
	}
	return ""
}

func (m *PushInfo) GetMdmTopic() string {
	if m != nil {
		return m.MdmTopic
	}
	return ""
}

func init() {
	proto.RegisterType((*PushInfo)(nil), "pushproto.PushInfo")
}

func init() { proto.RegisterFile("push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x28, 0x2d, 0xce,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0xa5, 0x02, 0x2e, 0x8e,
	0x80, 0xd2, 0xe2, 0x0c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x21, 0x2e, 0x96, 0xd2, 0x94, 0xcc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x3f, 0x3b,
	0x35, 0x4f, 0x82, 0x09, 0x2c, 0x08, 0xe1, 0x08, 0xc9, 0x42, 0x8c, 0x8b, 0xcf, 0x4d, 0x4c, 0xcf,
	0x4c, 0x96, 0x60, 0x06, 0x4b, 0x81, 0x0d, 0xf5, 0x05, 0x09, 0x08, 0x49, 0x73, 0x71, 0xe6, 0xa6,
	0xe4, 0xc6, 0x97, 0xe4, 0x17, 0x64, 0x26, 0x4b, 0xb0, 0x80, 0x65, 0x39, 0x72, 0x53, 0x72, 0x43,
	0x40, 0xfc, 0x24, 0x36, 0xb0, 0xc5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xd3, 0xd3,
	0x24, 0x91, 0x00, 0x00, 0x00,
}
